# This is the closest I could get to what I wanted, but it just wasn't close
# enough. So this file is unused. This is just here to save the result of this discovery work.

# https://github.com/JohnnyMorganz/StyLua?tab=readme-ov-file#options

column_width = 240
syntax = "LuaJIT"
line_endings = "Unix"
indent_type = "Spaces"
indent_width = 2
# quote_style = "AutoPreferDouble"
quote_style = "AutoPrefer"
call_parentheses = "Input"
space_after_function_names = "Never"
collapse_simple_statement = "Never"
