local lines = require("treewalker.lines")
local stub = require('luassert.stub')
local assert = require("luassert")
local load_fixture = require("tests.load_fixture")

describe("lines", function()
  describe(".get_line", function()
    it("gets the line", function()
      load_fixture("lua.lua", "lua")
      local line = lines.get_line(3)
      assert.equals("local M = {}", line)
    end)
  end)

  describe(".get_lines", function()
    it("gets the lines", function()
      load_fixture("lua.lua", "lua")
      local line = lines.get_lines(3, 4)
      assert.same({ "local M = {}", "" }, line)
    end)
  end)

  describe(".set_line", function()
    it("sets the line", function()
      load_fixture("lua.lua", "lua")
      lines.set_line(3, "whattup")
      assert.equal("whattup", lines.get_line(3))
    end)
  end)

  describe(".set_lines", function()
    it("gets the lines", function()
      load_fixture("lua.lua", "lua")
      lines.set_lines(3, 4, { "whattup", "wooo" })
      assert.same({ "whattup", "wooo" }, lines.get_lines(3, 4))
    end)
  end)

  describe(".get_indent", function()
    it("gets the line", function()
      load_fixture("lua.lua", "lua")
      local indent = lines.get_start_col("  local line = lines.get_indent()")
      assert.equals(3, indent)
    end)
  end)
end)
