local assert = require("luassert")
local load_fixture = require("tests.load_fixture")
local nodes = require("treewalker.nodes")

describe("nodes", function()
  before_each(function()
    load_fixture("/lua.lua")
  end)

  describe(".get_root", function()
    it("returns the root node for the current buffer", function()
      local root = nodes.get_root()
      assert.is_not_nil(root)
      assert.equal("chunk", root:type())
    end)

    it("returns the root node for a specific buffer", function()
      local bufnr = vim.api.nvim_get_current_buf()
      local root = nodes.get_root(bufnr)
      assert.is_not_nil(root)
      assert.equal("chunk", root:type())
    end)

    it("returns nil when parser is not available", function()
      load_fixture("/random.not_real", true) -- withhold_parsing = true
      local root = nodes.get_root()
      assert.is_nil(root)
    end)
  end)

  describe(".get_srow", function()
    it("returns 1-indexed start row", function()
      local node = nodes.get_at_row(1)
      assert.is_not_nil(node)
      local srow = nodes.get_srow(node)
      assert.equal(1, srow)
    end)

    it("returns correct row for nodes not at line 1", function()
      local node = nodes.get_at_row(3)
      assert.is_not_nil(node)
      local srow = nodes.get_srow(node)
      assert.equal(3, srow)
    end)
  end)

  describe(".get_erow", function()
    it("returns 1-indexed end row", function()
      local node = nodes.get_at_row(1)
      assert.is_not_nil(node)
      local erow = nodes.get_erow(node)
      assert.is_true(erow >= 1)
    end)

    it("returns end row greater than or equal to start row", function()
      vim.fn.cursor(21, 1) -- function line
      local node = vim.treesitter.get_node()
      assert.is_not_nil(node)
      local srow = nodes.get_srow(node)
      local erow = nodes.get_erow(node)
      assert.is_true(erow >= srow)
    end)
  end)

  describe(".get_scol", function()
    it("returns 1-indexed start column", function()
      local node = nodes.get_at_row(1)
      assert.is_not_nil(node)
      local scol = nodes.get_scol(node)
      assert.equal(1, scol)
    end)

    it("returns correct column for indented nodes", function()
      vim.fn.cursor(22, 3) -- indented line
      local node = vim.treesitter.get_node()
      assert.is_not_nil(node)
      local scol = nodes.get_scol(node)
      assert.is_true(scol >= 1)
    end)
  end)

  describe(".get_at", function()
    it("returns node at specified position", function()
      local node = nodes.get_at(1, 1)
      assert.is_not_nil(node)
    end)

    it("returns nil for invalid positions", function()
      local node = nodes.get_at(9999, 1)
      assert.is_nil(node)
    end)
  end)

  describe(".get_at_row", function()
    it("returns node at specified row", function()
      local node = nodes.get_at_row(1)
      assert.is_not_nil(node)
    end)

    it("returns node at first non-whitespace column", function()
      local node = nodes.get_at_row(22) -- indented line
      assert.is_not_nil(node)
    end)

    it("returns nil for empty rows beyond file end", function()
      local node = nodes.get_at_row(9999)
      assert.is_nil(node)
    end)
  end)

  describe(".get_lines", function()
    it("returns lines of text for a single-line node", function()
      local node = nodes.get_at_row(1)
      assert.is_not_nil(node)
      local text_lines = nodes.get_lines(node)
      assert.is_table(text_lines)
      assert.is_true(#text_lines >= 1)
    end)

    it("returns multiple lines for multi-line nodes", function()
      vim.fn.cursor(21, 1)
      local node = vim.treesitter.get_node()
      -- Find a multi-line parent
      while node and nodes.get_srow(node) == nodes.get_erow(node) do
        node = node:parent()
      end
      if node then
        local text_lines = nodes.get_lines(node)
        assert.is_true(#text_lines > 1)
      end
    end)
  end)

  describe(".have_same_srow", function()
    it("returns true for nodes on the same row", function()
      local node1 = nodes.get_at(1, 1)
      local node2 = nodes.get_at(1, 10)
      assert.is_not_nil(node1)
      assert.is_not_nil(node2)
      assert.is_true(nodes.have_same_srow(node1, node2))
    end)

    it("returns false for nodes on different rows", function()
      local node1 = nodes.get_at(1, 1)
      local node2 = nodes.get_at(3, 1)
      assert.is_not_nil(node1)
      assert.is_not_nil(node2)
      assert.is_false(nodes.have_same_srow(node1, node2))
    end)
  end)

  describe(".have_same_scol", function()
    it("returns true for nodes at the same column", function()
      local node1 = nodes.get_at(1, 1)
      local node2 = nodes.get_at(3, 1)
      assert.is_not_nil(node1)
      assert.is_not_nil(node2)
      -- Both should start at column 0 (0-indexed internally)
      assert.is_true(nodes.have_same_scol(node1, node2))
    end)

    it("returns false for nodes at different columns", function()
      local node1 = nodes.get_at(1, 1) -- top level
      local node2 = nodes.get_at(22, 5) -- indented
      assert.is_not_nil(node1)
      assert.is_not_nil(node2)
      -- Different columns
      local _, scol1 = node1:range()
      local _, scol2 = node2:range()
      if scol1 ~= scol2 then
        assert.is_false(nodes.have_same_scol(node1, node2))
      end
    end)
  end)

  describe(".range", function()
    it("returns a table with 4 elements", function()
      local node = nodes.get_at_row(1)
      assert.is_not_nil(node)
      local range = nodes.range(node)
      assert.is_table(range)
      assert.equal(4, #range)
    end)

    it("returns correct range values", function()
      local node = nodes.get_at_row(1)
      assert.is_not_nil(node)
      local range = nodes.range(node)
      local r1, r2, r3, r4 = node:range()
      assert.same({ r1, r2, r3, r4 }, range)
    end)
  end)

  describe(".whole_range", function()
    it("returns min and max rows for a single node", function()
      local node = nodes.get_at_row(1)
      assert.is_not_nil(node)
      local range = nodes.whole_range({ node })
      assert.is_table(range)
      assert.equal(2, #range)
      assert.is_true(range[1] <= range[2])
    end)

    it("returns spanning range for multiple nodes", function()
      local node1 = nodes.get_at_row(1)
      local node2 = nodes.get_at_row(3)
      assert.is_not_nil(node1)
      assert.is_not_nil(node2)
      local range = nodes.whole_range({ node1, node2 })
      assert.is_table(range)
      assert.equal(0, range[1]) -- 0-indexed start
      assert.is_true(range[2] >= 2) -- 0-indexed, at least row 3
    end)
  end)

  describe(".lsp_range", function()
    it("returns LSP-formatted range", function()
      local node = nodes.get_at_row(1)
      assert.is_not_nil(node)
      local lsp_range = nodes.lsp_range(node)
      assert.is_table(lsp_range)
      assert.is_table(lsp_range.start)
      assert.is_table(lsp_range["end"])
      assert.is_number(lsp_range.start.line)
      assert.is_number(lsp_range.start.character)
      assert.is_number(lsp_range["end"].line)
      assert.is_number(lsp_range["end"].character)
    end)

    it("has correct LSP range structure", function()
      local node = nodes.get_at_row(1)
      assert.is_not_nil(node)
      local lsp_range = nodes.lsp_range(node)
      local srow, scol, erow, ecol = node:range()
      assert.equal(srow, lsp_range.start.line)
      assert.equal(scol, lsp_range.start.character)
      assert.equal(erow, lsp_range["end"].line)
      assert.equal(ecol, lsp_range["end"].character)
    end)
  end)
end)
