name: Tests

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ main ]

jobs:
  luacheck:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Run luacheck type check / linter
      run: |
        sudo apt-get install lua-check -y --no-install-recommends
        make check


  test:
    strategy:
      matrix:
        neovim_version: ['v0.9.5', 'v0.10.2', 'stable', 'nightly']
      fail-fast: false

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Neovim
      uses: rhysd/action-setup-vim@v1
      with:
        neovim: true
        version: ${{ matrix.neovim_version }}

    - name: Install Plenary
      run: |
        mkdir -p $HOME/.local/share/nvim/lazy/
        git clone https://github.com/nvim-lua/plenary.nvim.git
        mv plenary.nvim $HOME/.local/share/nvim/lazy/

    - name: Install nvim-treesitter
      run: |
        mkdir -p $HOME/.local/share/nvim/lazy/
        git clone https://github.com/nvim-treesitter/nvim-treesitter.git
        mv nvim-treesitter $HOME/.local/share/nvim/lazy/

    - name: Check for errant util calls
      run: make no-utils

    - name: Run Tests
      run: make test

